deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /opt/cpanel/ea-nodejs16/bin/npm install
    - /opt/cpanel/ea-nodejs16/bin/npm run build
    - /bin/cp -R dist/* $DEPLOYPATH
